from random import randint
from dataclasses import dataclass, field
from .codon import Codon, START_SEQUENCE, END_SEQUENCE

GENES = [
    "ATGGGGAACCTAGGTGATTACGATGGCCCCGAAAGCGTGTGAACCACAGGAGCGGATAACAAGCAGTCGATCTTGCGCAGATATGTGCTTGGTTTACAGAAGAAAAAGGATTATCCTTATCGCGTATGACTTTCCATGTCCCGCTGTGCCAAATGTGCACAGTTATGTCTTGGGTTCAGTGCGTTCCAGGTTGTGGGTTTTGACAATAGACCGCTGCGGGTCTTTAATCACGGCAGTTCTGGTCAGCATGACCCTAGCTGACGAAACACTTGCGGTTATTAGTAA",
    "ATGGAACACTGTCGTGATGAATGCTGTTTACATCCCTATCCTCGCTTCCCTTGTACCGAGATCTCAACCTAGTTTACTGGTTTCAGCCTAAGCCGTTAGTGTGGCCCGGTTGACTCGAGCAGGACTCGGATCGTGCTCACGTACCAAACCCTATCGGGTTATGAGGGAGGTTTGGAGCTTCTTGGTGAAACCCTCAGTGCCGCACCCGCGGCAGGGCTAAAACCTCTAAACAGCAGACGCCCTCATCGCTCCGGGTAA",
    "ATGAGACTATCTAGAGAAGGATCGAAAGGGTAGCACCCGGTTCCATTACGCCCTATGAGGATCATGTTGGTCCAAACGTACCATATCCATACGGCCATCACCGGTTCTAGGCCGTCTTACATTTACTTCTAGGGTAATTTACCCCCACCCCTGGCCGGTTGTGAAAAACAATCTTGTGGCAACGTCGCAACATGGGACACGAGAGCCCTTCGCCGAGTGTAA",
    "ATGCATACGTTGTAACCCTACTTCGTTGGAAAAGGATCTTCAGAGATTTATCGCCCGCAGGCGATAGAAGGACAGACCAAAGTCTCAATCCCCAGCTCGGTAGTCCAGCTTACAGTACTGTGTATACGCCCTAATCACCCCCGCGGCGGTAAGCGATACTTGCCCGCCATAAAGCGATGAGCTGCTGCTTTCAGGAGTGGGATTAGCTAAAGTTGAGACTAGAAGTATGGTAATTCTATAAGGCTGTTACGCTGATTCTAGGAAGAGGCGGACCGGAGTTCTATATTGTAA",
    "ATGACGCCACGAGGACAGAAGCTGCGGGCCAAGCGATACCGTCAATCTGTTGTGCGGCCTAATTTTTGGTTGCCATAGGGCAGGGTGAAGATCCTGAGATCTTACCATTATCAGACGGTGTGCACGGAGCCTCGCTGACCGTGGGGGTATATTGTGGGATCTCGATACTGGGTAGTCACCCGGAAAACCCCGCACCAACGAGGATAA"
]


@dataclass
class Gene:
    codons: list[Codon] = field(default_factory=list)

    def __str__(self):
        return f"{START_SEQUENCE}{''.join([str(x) for x in self.codons])}{END_SEQUENCE}"

    @classmethod
    def from_random(cls):
        r = randint(50, 100)
        codons = []
        for i in range(r):
            codons.append(Codon.from_random())
        return cls(codons=codons)

    @classmethod
    def from_string(cls, gene_string: str):
        codons = []
        for i in range(0, len(gene_string), 3):
            codon_string = gene_string[i:i + 3]
            codons.append(Codon.from_string(codon_string))
        return cls(codons=codons)
